/*
 * Automatically generated by jrpcgen 1.1.3 on 17-5-4 обнГ10:31
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package LockService;
/**
 * A collection of constants used by the "LockService" ONC/RPC program.
 */
public interface LockService {
    public static final int LockService = 1;
    public static final int tryAcquire_1 = 1;
    public static final int LockServiceVERS = 1;
}
// End of LockService.java
